"""Checks that transcript.py labels who wrote each user record, using the
same classifier as scan.sh. Prints one token per user record: kind, plus
the command name for commands. With "chapters", prints the transcript page's
chapters for the same session instead (via chapters-probe.js)."""
import json, os, sys, tempfile, shutil, subprocess

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, "..", "..", "lib"))
import transcript


def u(text, **kw):
    return json.dumps({"type": "user", "uuid": f"u{len(LINES)}", "message": {"role": "user", "content": text}, **kw})


LINES = []
for line in (
    lambda: u("<command-name>/clear</command-name><command-message>clear</command-message><command-args></command-args>"),
    lambda: u("<local-command-caveat>Caveat: generated by local commands</local-command-caveat>", isMeta=True),
    lambda: u("<command-message>catchup</command-message><command-name>/catchup</command-name><command-args>at x.md</command-args>",
              origin={"kind": "human"}),
    lambda: u("Base directory for this skill: /skills/catchup", isMeta=True),
    lambda: u("fix the tab bug", origin={"kind": "human"}),
    lambda: u("<task-notification><summary>Agent \"seat\" finished</summary></task-notification>",
              origin={"kind": "task-notification"}),
    lambda: u("Stop hook feedback: goal not met", isMeta=True),
    lambda: u('Another Claude session sent a message: <teammate-message teammate_id="rev" summary="done">x</teammate-message>'),
    lambda: u("<local-command-stdout>Goal set</local-command-stdout>"),
):
    LINES.append(line())


def a(text, n):
    return json.dumps({"type": "assistant", "uuid": f"a{n}", "message": {
        "id": f"m{n}", "model": "claude-opus-5-5", "role": "assistant",
        "content": [{"type": "text", "text": text}], "usage": {}}})


if sys.argv[1:] == ["tail"]:
    # an idle card whose newest lines are a hook and a mode change
    think = json.dumps({"type": "assistant", "uuid": "th1", "message": {"id": "m9", "model": "claude-opus-5-5",
        "role": "assistant", "content": [{"type": "thinking", "thinking": "weighing it"}], "usage": {}}})
    LINES += [a("On it.", 1), u("second ask", origin={"kind": "human"}), a("Done.", 2), think,
              u("Stop hook feedback: goal not met", isMeta=True),
              json.dumps({"type": "permission-mode", "permissionMode": "bypassPermissions"})]
if sys.argv[1:] == ["chapters"]:
    # after the owner's ask: Claude answers, a command runs with a reply and
    # no typed message after it, then a command with nothing after it at all
    # a session that opens with only its permission mode has no "Session start" chapter
    LINES.insert(0, json.dumps({"type": "permission-mode", "permissionMode": "default"}))
    LINES.insert(1, u("<local-command-caveat>Caveat: local commands</local-command-caveat>", isMeta=True))
    LINES += [a("On it.", 1), u("second ask", origin={"kind": "human"}), a("Done.", 2),
              u("<command-name>/review</command-name><command-args></command-args>", origin={"kind": "human"}),
              a("## Review\nLooks fine.", 3),
              u("<command-name>/model</command-name><command-args></command-args>")]

if sys.argv[1:] == ["modes"]:
    # Claude Code writes a "mode" line (always "normal", the input mode) beside
    # every "permission-mode" line; only the second is a permission mode.
    normal = json.dumps({"type": "mode", "mode": "normal"})
    perm = lambda pm: json.dumps({"type": "permission-mode", "permissionMode": pm})
    LINES = [normal, perm("bypassPermissions"), u("one", origin={"kind": "human"}), a("ok", 1),
             normal, perm("bypassPermissions"), u("two", origin={"kind": "human"}), a("ok", 2),
             normal, perm("auto"), u("three", origin={"kind": "human"})]

root = tempfile.mkdtemp(prefix="turns-")
try:
    p = os.path.join(root, "s.jsonl")
    with open(p, "w") as fh:
        fh.write("\n".join(LINES) + "\n")
    res = transcript.parse_transcript(p)
    recs = res["records"]
    if sys.argv[1:] == ["modes"]:
        flips = [r["text"].split("→ ")[-1] for r in recs if r.get("event_type") == "mode-change"]
        print(" ".join(flips), "| now", res["meta"]["permission_mode"])
        sys.exit(0)
    if sys.argv[1:] in (["chapters"], ["tail"]):
        rp = os.path.join(root, "records.json")
        with open(rp, "w") as fh:
            json.dump(recs, fh)
        run = subprocess.run(["node", os.path.join(HERE, sys.argv[1] + "-probe.js"), rp],
                             capture_output=True, text=True)
        print((run.stdout or run.stderr).strip())
        sys.exit(0)
    out = []
    for r in recs:
        if r.get("role") != "user":
            continue
        k = r.get("turn") or "-"
        out.append(k + (":" + r["command"] if r.get("command") else ""))
    print(" ".join(out))
finally:
    shutil.rmtree(root, ignore_errors=True)
